services:

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=mysql-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ./dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    networks:
      - app-network

  app:
    image: app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat-app
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/mysql-db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local